version: "3.9"

services: 
  nginx:
    image: nginx:1.21.1
    container_name: php_nginx
    ports:
      - 8090:90
    networks:
      - web_dev
    volumes:
      - ./.docker/server/:/etc/nginx/conf.d/
      - ./src:/var/www

  php:
    build: .
    container_name: php_fpm
    volumes: 
      - ./src:/var/www
    ports: 
      - "9000:9000"
    networks: 
      - web_dev

  mysql:
    image: mysql:8.0.26
    container_name: php_mysql
    volumes: 
      - ./.docker/db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - 3306:3306
    networks: 
      - web_dev

networks: 
  web_dev:
    driver: bridge